name: CI-Label

on:
  push:
    branches:
    - master
  pull_request:
    types: [ labeled ]
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  MAJOR_MINOR_VERSION: 0.1.

jobs:
  build:
    if: ${{ github.event.label.name == 'Ready to Deploy' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo "The PR number - ${{ github.event.pull_request.number }}"
      
